### ISSUE TITLE
LaunchNow URL withVPC parameter does not work

### ISSUE THREAD

**Issue by paoliniluis** [awsdocs/aws-elastic-beanstalk-developer-guide#105]
Hi, when launching a docker instance on ElasticBeanstalk with the URL parameter "&withVpc=true" it does not create a VPC and the instance fails to start saying that the instance type needs a VPC.

Steps to reproduce:
1) Build a LaunchNow URL with: https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-2#/newApplication?applicationName=anyApp&platform=Docker&environmentType=LoadBalancing&tierName=WebServer&instanceType=t3a.small&withVpc=true&withRds=false
2) Click on "Review and Launch" (you can leave the sample application option selected)
3) see in the next page that the VPC is not auto-created
![image](https://user-images.githubusercontent.com/1711649/103678574-726bf880-4f62-11eb-96fe-71063f6ac222.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
