### ISSUE TITLE
postgres not supported?

### ISSUE THREAD

**Issue by paoliniluis** [awsdocs/aws-elastic-beanstalk-developer-guide#106]
postgres is not an option in "rdsDBEngine" variable but works when entered as a parameter, will postgreSQL be deprecated in the future in ElasticBeanstalk?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
