### ISSUE TITLE
dotnet core tutorial leads to errors

### ISSUE THREAD

**Issue by mtsanaissi** [awsdocs/aws-elastic-beanstalk-developer-guide#111]
Following the instructions on [dotnet-core-tutorial](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/main/doc_source/dotnet-core-tutorial.md) did not work as expected.
When trying to deploy the source bundle to the created environment, the error below is shown.
`Instance deployment: Your source bundle has a single .NET Core application. You must include a file with a '.runtimeconfig.json' suffix. The deployment failed.`
I found this [StackOverflow answer](https://stackoverflow.com/a/65650000) explaining the correct way to deploy.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
