### ISSUE TITLE
Need new sample for Multicontainer Docker, Current one is deprecated

### ISSUE THREAD

**Issue by bannarisoftwares** [awsdocs/aws-elastic-beanstalk-developer-guide#119]

**Comment by mrenneke-amazon** [comment]
Hello @bannarisoftwares --
Beanstalk released a new platform branch that is a supported version of the deprecated Multicontainer Docker platform.  
For more information, see:
* [Release: Elastic Beanstalk introduces ECS running on Amazon Linux 2 to Docker platform ](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-03-25-ecsal2.html)
* [Using the Amazon ECS platform branch](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html)

Thank you for your comment!
