### ISSUE TITLE
the screenshots do not match what is shown in Visual Studio 2013

### ISSUE THREAD

**Issue by GregSansoni** [awsdocs/aws-elastic-beanstalk-developer-guide#12]
I am using VS2013 professional. I have AWS Toolkit for .NET installed:
AWSToolsAndSDKForNet_sdk-3.3.250.0_ps-3.3.245.0_tk-1.14.1.6

The screenshots in the following section:
https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/dotnet-toolkit.md

do not match the wizard that I see when I deploy the app.  It appears that the documentation's example applies to a "Legacy wizard" because if I click "Use legacy wizard.." I will see these screenshots. 

I would suggest updating doc to match the latest wizard that AWS Toolkit for Visual Studio users will see.

**Comment by dankhen** [comment]
Thanks @GregSansoni. Yes, we are well aware that many older Elastic Beanstalk developer guide topics, mainly around the platform tutorials, are in need of a refresh. It's on our plans. We hope to be able to get to it soon.
Thanks for drawing our attention to this particular one.
