### ISSUE TITLE
Confusion around RAILS_SKIP_ASSET_COMPILATION on configdeploy

### ISSUE THREAD

**Issue by tschaub** [awsdocs/aws-elastic-beanstalk-developer-guide#120]
I was surprised to find that `bundle exec rake assets:precompile` is not run on `config-deploy` (or when `ENV` vars are edited).  In a Rails project that uses webpacker (which I think is common), this means that editing `ENV` vars will result in a broken deployment.

It looks like [the solution](https://stackoverflow.com/questions/62600427/elastic-beanstalk-is-causing-my-rails-6-app-precompiled-assets-to-break-when-add) is to add a `.platform/confighooks/predeploy` script, though that feels a bit fiddly to get the proper env set up and ensure ownership is correct after `rake assets:precompile`.

[The docs](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/main/doc_source/create_deploy_Ruby.container.md) mention a `RAILS_SKIP_ASSET_COMPILATION` setting that sounds somewhat related.  The docs refer to "deployment," and I'm guessing that this is different than `config-deploy` or "configdeploy".  I'm uncertain what the default behavior is, but it looks like `rake assets:precompile` is run on a full deployment (e.g. triggered by a CodePipeline) but not on a config deployment (triggered by an environment variable change).

Is there a "built in" way to get `rake assets:precompile` to run after making a configuration change (e.g. `ENV` var change)?

**Comment by tschaub** [comment]
See also https://github.com/aws/elastic-beanstalk-roadmap/issues/59#issuecomment-847405152.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
