### ISSUE TITLE
Custom Log Streaming references deprecated documentation

### ISSUE THREAD

**Issue by bananastalktome** [awsdocs/aws-elastic-beanstalk-developer-guide#136]
The CloudWatch Logs Agent Reference link in the "Custom Log Streaming" section of https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.cloudwatchlogs.html references the deprecated CloudWatch Logs agent reference page. Additionally, the [logs-streamtocloudwatch-linux.config](https://github.com/awsdocs/elastic-beanstalk-samples/tree/master/configuration-files/aws-provided/instance-configuration/logs-streamtocloudwatch-linux.config) links beanstalk config that also appears to use the deprecated agent.

The code is at: https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/c39ee0885f3967b2bfc80cb968505d0e794ff5f0/doc_source/AWSHowTo.cloudwatchlogs.md?plain=1#L176-L183

Is there a non-deprecated reference for Custom Log Streaming configuration (maybe using the unified CloudWatch Agent) that can be referenced here instead? Depsite deprecation, is there any guidance as to whether the CloudWatch Logs agent should continue to be used (as its inclusion in the Beanstalk documentation suggests)?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
