### ISSUE TITLE
Cannot set URL with scheme

### ISSUE THREAD

**Issue by beobungbu** [awsdocs/aws-elastic-beanstalk-developer-guide#137]
when I define a key named API with contains a value like: http://git.com/sba,
 the .env file in the EC2 instance only:
`API=http:/`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
