### ISSUE TITLE
Django Tutorial missing required steps

### ISSUE THREAD

**Issue by huribeir** [awsdocs/aws-elastic-beanstalk-developer-guide#14]
Hello,

currently if the [Django Tutorial](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/create-deploy-python-django.md) is followed strictly, the resulting application is not going to open with the following Django error displayed on the Beanstalk-generated URL:

 "Invalid HTTP_HOST header"

This is due to the Beanstalk URL not being explicitly allowed in the django settings.py [ALLOWED_HOSTS](https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts) option.

Ideally, the instructions should cover this step so the tutorial provides a fully working example.

**Comment by dankhen** [comment]
Hello @huribeir,
To make sure I understand which change exactly you are proposing, would you be able to create a pull request on [the tutorial](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/create-deploy-python-django.md), with the missing step? TIA!

**Comment by dankhen** [comment]
Wonderful, I am closing this issue and we will track on the PR. Thanks!
