### ISSUE TITLE
Django tutorial seems to be missing a step for serving static resources. 

### ISSUE THREAD

**Issue by jonmooser** [awsdocs/aws-elastic-beanstalk-developer-guide#140]
The tutorial explains how to set the STATIC_ROOT, and how to run collectstatic.
But it is missing the key step of adding  .ebextensions/static-files.config
Without that, the environment won't actually serve the static resources.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
