### ISSUE TITLE
Python example lacks hint about need for additional steps when using MySQL database 

### ISSUE THREAD

**Issue by fkromer** [awsdocs/aws-elastic-beanstalk-developer-guide#147]
The [Working with Python - Adding a database](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/main/doc_source/create-deploy-python-rds.md#downloading-a-driver) section is missing a hint that there is need to adjust .ebextensions in case when trying to connect to a MySQL database. The fix is documented on [stackoverflow](https://stackoverflow.com/a/62116473/5308983).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
