### ISSUE TITLE
eb init -p docker results in ERROR: NotSupportedError - You can use "eb local" only with preconfigured, generic and multicontainer Docker platforms.

### ISSUE THREAD

**Issue by michalani** [awsdocs/aws-elastic-beanstalk-developer-guide#149]
When following https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker.html#single-container-docker.test-local to create a local test for docker you are likely to get into:

```
Admin:~/environment/eb-flask $ eb init -p docker application-name                       
Admin:~/environment/eb-flask $ eb local run --port 5000
ERROR: NotSupportedError - You can use "eb local" only with preconfigured, generic and multicontainer Docker platforms.
```

This is because the documentation does not adequately highlight the fact that -p `docker`  value should be changed which usually is done by the `red colour` within AWS documentation. This currently can only be seen in the 2nd argument which is the `application-name` this results in confusion which is caused either from the documentation or EB CLI side.

A workaround for this would be using `eb init -p "Docker running on 64bit Amazon Linux 2" application-name`

Alternative workaround would be to use `eb init` and select `docker` as a platform when setting this up.

Please update the command directly on https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/main/doc_source/docker.md

**Comment by mrenneke-amazon** [comment]
Thanks for pointing this out @michalani !  We're working on making these changes.  Stay tuned for an update!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
