### ISSUE TITLE
EB docs refer to EC2Config and not EC2Launch when creating custom Windows AMIs

### ISSUE THREAD

**Issue by michalani** [awsdocs/aws-elastic-beanstalk-developer-guide#152]
When following `Using a custom Amazon machine image (AMI)` documentation in step 7 we can see:
```
(Windows platforms) Run the EC2Config service Sysprep. For information about EC2Config, see Configuring a Windows Instance Using the EC2Config Service. Ensure that Sysprep is configured to generate a random password that can be retrieved from the AWS Management Console.
```

Documentation source:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.customenv.html#using-features.customenv.create
https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/main/doc_source/using-features.customenv.md

The documentation specifies to use EC2Config, this tool has been replaced with EC2Launch as per https://repost.aws/knowledge-center/sysprep-create-install-ec2-windows-amis

You can find the same here https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/Creating_EBSbacked_WinAMI.html#ami-create-standard
```
If you use Sysprep to create a standardized AMI, we recommend that you run Sysprep with EC2Launch v2. If you are still using the EC2Config (Windows Server 2012 R2 and earlier) or EC2Launch (Windows Server 2016 and 2019) agents, see the documentation for using Sysprep with EC2Config and EC2Launch below.
```

Please change the wording so that it's specified whether the EC2Launch or EC2Config is needed to be run

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
