### ISSUE TITLE
alarms documentation out of date for new console look

### ISSUE THREAD

**Issue by michalani** [awsdocs/aws-elastic-beanstalk-developer-guide#153]
Hello there,

The steps for the alarms are out of date and do not conform to the new console. Some buttons have been completely removed while others have been moved around.

This is a request to update the documentation to reflect the consoles changes.

Documentation in question:
1. https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.alarms.html
2. https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/main/doc_source/using-features.alarms.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
