### ISSUE TITLE
French localization for concepts-webserver.md displays title in japanese

### ISSUE THREAD

**Issue by ajoga** [awsdocs/aws-elastic-beanstalk-developer-guide#19]
Title says it all. If I'm not mistaken the localized pages are not on GitHub, nor can we submit pull request anywhere, right ?

![screenshot from 2018-04-12 10-38-57](https://user-images.githubusercontent.com/37543966/38665850-bbc2581e-3e3d-11e8-8fec-f59f81ed89fb.png)

**Comment by dankhen** [comment]
You are correct @ajoga, we only have the English version on GitHub.
Thanks for reporting the issue to us!
I checked and our localization team already has an open bug on this issue.
