### ISSUE TITLE
French localization for using-features.managing.as.md displays title partially in japanese

### ISSUE THREAD

**Issue by ajoga** [awsdocs/aws-elastic-beanstalk-developer-guide#30]
Hello, 

Same thing as #19 but for another page : 

![screenshot from 2018-06-20 09-52-03](https://user-images.githubusercontent.com/37543966/41644943-dda95bae-746f-11e8-99bc-ed72b2d75b35.png)

https://docs.aws.amazon.com/fr_fr/elasticbeanstalk/latest/dg/using-features.managing.as.html

I quickly checked all the other title on the side menu if there was other occurrences of this issue. It appears there is no other title in Japanese at the time of writing this ticket. 

AJ

**Comment by dankhen** [comment]
Thank you @ajoga for bringing this to our attention! I'll forward this info to our localization team.
