### ISSUE TITLE
Changelog for the Multi-container Docker running on 64bit Amazon Linux/2.11.0

### ISSUE THREAD

**Issue by Trane9991** [awsdocs/aws-elastic-beanstalk-developer-guide#31]
Hello,
I'm noticed on the console that `Multi-container Docker running on 64bit Amazon Linux/2.11.0` already live, but I can't see the release notes and changelog for this version.

**Comment by dankhen** [comment]
Hi @Trane9991 ,
Thanks for pointing it out! Our documentation publishing process took a bit longer into the evening (Seattle time) to complete during this recent update, and I was out of office the next day. Therefore, while the HTML documents on our web site were up to date at the end of day Friday, the GitHub version wasn't. I just ran the update and the GitHub guide is now up to date.
