### ISSUE TITLE
Security group inconsistency in AWSHowTO.RDS.md

### ISSUE THREAD

**Issue by fbukevin** [awsdocs/aws-elastic-beanstalk-developer-guide#37]
In [Using Elastic Beanstalk with Amazon Relational Database Service](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/AWSHowTo.RDS.md)

There is a line saying:
> For Source, type sg- to view a list of available security groups. Choose the current security group to allow resources in the security group to receive traffic on the database port from other resources in the same group.

It mentions that **choose the current security group**. While look to picture of step 5 (RDS instance detail) and step 10 (Choose security group source), the two security group and ID seem inconsistent. In step 5, the security group is `rds-launch-wizard-3(sg-a745c5cc)`, whereas security group in step 10 is `rds-launch-wizard(sg-0e6259e645e4440a8)`.

Step 5
![step5](https://camo.githubusercontent.com/9a52c212aa12f2bb50fe30b05fbf79a1edb0ede0/687474703a2f2f646f63732e6177732e616d617a6f6e2e636f6d2f656c61737469636265616e7374616c6b2f6c61746573742f64672f696d616765732f7264732d736563757269747967726f75702e706e67)

Step 10
![step10](https://camo.githubusercontent.com/b22cd3a640676aa0c8a0da827d78413dd5ca85d8/687474703a2f2f646f63732e6177732e616d617a6f6e2e636f6d2f656c61737469636265616e7374616c6b2f6c61746573742f64672f696d616765732f6563322d736563757269747967726f75702d7264732e706e67)

Should both of them be the same one?

**Comment by dankhen** [comment]
@fbukevin, thanks for pointing this out. Looks like these two screenshots were updated at different times and are therefore inconsistent. We'll work on fixing it.

**Comment by dankhen** [comment]
Quick follow-up: this is now fixed. I also took the opportunity to fix an RDS console procedure that was outdated. Thanks again @fbukevin for pointing out the issue.
