### ISSUE TITLE
Express Application steps are out of order

### ISSUE THREAD

**Issue by finchd** [awsdocs/aws-elastic-beanstalk-developer-guide#46]
If you `eb create` with an express app following the instructions at [doc_source/create_deploy_nodejs_express.md](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/create_deploy_nodejs_express.md), the environment fails and the stack is in CREATE_FAILED.

Running `express` and `npm start` in the directory then requires the .ebextensions/nodecommand.config which is not added unless you also perform the "Update the Application" set of steps.
This should not be separate from the "Create an Elastic Beanstalk Environment" set, since skipping it creates unusable environments.

Please move creating the .ebextension into "Create an Elastic Beanstalk Environment".

**Comment by alivest** [comment]
Thanks! Can you please edit your comment to include the following statement?
"By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice."

**Comment by alivest** [comment]
Woops, thought it was a PR. Thanks for the suggestion! We'll look into it and verify.

**Comment by alivest** [comment]
Hello! 
I was not able to reproduce this issue, so you may have experienced something slightly different than we thought. Here are a couple suggestions I have: 
* Check your current EB CLI version, the expected version should be EB CLI 3.7.8 (Python 3.4.3)
* Make sure you're deploying the Beanstalk sample first with `eb create --sample node-express-env`, the generated express application will fail without the .ebextension added in that step. 

If neither of those options help, here are our other support resources:
* Try our forum: https://forums.aws.amazon.com/forum.jspa?forumID=86
* or, Contact AWS Support: https://aws.amazon.com/premiumsupport/

And thanks for reaching out!
