### ISSUE TITLE
database in django example

### ISSUE THREAD

**Issue by nwolff** [awsdocs/aws-elastic-beanstalk-developer-guide#47]
Hi, I ran into this page https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-django.html when googling how to automatically create the django superuser on the beanstalk instance.

When reading thru the article quickly I first thought it provided a solution but then I understood the article talks of using an sqlite db, and shipping it over to the beanstalk instance with every deployment, thus overwriting the database on the server.

I understand that this article is only about a 'sample app', but I still suggest you consider updating the documentation to use RDS.

**Comment by dankhen** [comment]
Hi @nwolff ,

I believe that the topic right after that one, [Adding an Amazon RDS DB Instance to Your Python Application Environment](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-rds.html), covers what you're looking for.

**Comment by nwolff** [comment]
Hi @dankhen,

I've been running django with RDS and beanstalk for a few years so I am not looking for a tutorial.
I am merely saying that suggesting to new users to use an sqlite db and overwrite the database with each deployment seems to me like a bad advice, especially for newcomers.
