### ISSUE TITLE
Feedback on `eb create` error message

### ISSUE THREAD

**Issue by pavopax** [awsdocs/aws-elastic-beanstalk-developer-guide#54]
_Hi team, not sure where to place this. This is for AWS elastic beanstalk CLI application_

When creating a new environment in an application with `eb create`, I get an error which I think could be clarified:
```
ERROR: ValidationError - Parameter validation failed:
Invalid length for parameter EnvironmentName, value: 3, valid range: 4-inf
```

It is not immediately clear that this error refers to the first parameter I pass to `eb create`, *especially* since right above it I got `Upload complete` which suggested that command was ran successfully.

 I think we can make the error message easier to understannd for more users with something like:

`The name of the environment you are creating must be at least 4 characters long. Currently it is 3.` 

Or something similar.

### full error

I ran `eb create viz --.....` and got:

```bash
Creating application version archive "xxx".
Uploading dash-python/app-XXX.zip to S3. This may take a while.
Upload Complete.
ERROR: ValidationError - Parameter validation failed:
Invalid length for parameter EnvironmentName, value: 3, valid range: 4-inf
```

**Comment by dankhen** [comment]
Thanks @pavopax , definitely room for improvement here. I'll pass it on to the EB CLI team.

**Comment by neilharrisbrown** [comment]
+1
