### ISSUE TITLE
Feedback on `eb deploy` error

### ISSUE THREAD

**Issue by agalligani** [awsdocs/aws-elastic-beanstalk-developer-guide#55]
When I do an `eb deploy` I receive the following error - ERROR: TypeError - Can't convert 'NoneType' object to str implicitly

I'm assuming it's a python version issue but was pretty sure I have the correct version of Python (3.4.3)

`eb create` works correctly

**Comment by dankhen** [comment]
No follow-up for a long time - closing.
@agalligani, feel free to reopen with the additional information if this is still an issue. Thanks!
