### ISSUE TITLE
deploying application issue

### ISSUE THREAD

**Issue by hiteish** [awsdocs/aws-elastic-beanstalk-developer-guide#60]
I am getting following error , when I deploy the bundle. can can one help with it ?

The configuration file __MACOSX/eb-node-express-sample-v1-2/.ebextensions/._create-sns-topic.config in application version eb-node-express-sample-v1-2 contains invalid YAML or JSON. YAML exception: Invalid Yaml: unacceptable character '&#0;' (0x0) special characters are not allowed in "<reader>", position 0, JSON exception: Invalid JSON: Unexpected character (&#0;) at position 0.. Update the configuration file.

**Comment by dankhen** [comment]
Hello @hiteish,

It looks like your configuration file contains an invalid (and invisible) character at the top. Could be an artifact of the editor you used to prepare the file.

We can't provide more specific help here; this repo is for discussing issues with, or suggesting edits of, the documentation, and not meant as a service support forum. If you need more help, I can suggest the following:
- Our forum: https://forums.aws.amazon.com/forum.jspa?forumID=86
- AWS Support: https://aws.amazon.com/premiumsupport/

Thanks!

**Comment by hiteish** [comment]
thank you I have already managed to fix this.

and deploy app. but I don't understand why instance status is going RED and I can't find the table in DB . ? :( 

do you know this issue ?

**Comment by dankhen** [comment]
@hiteish, I recommend that you use one of the support channels I mentioned above. The forum is monitored by many Elastic Beanstalk experts.
