### ISSUE TITLE
Outdated release notes table in Worker Tier documentation

### ISSUE THREAD

**Issue by Kausheel** [awsdocs/aws-elastic-beanstalk-developer-guide#62]
The Worker Tier documentation contains a table which describes recently released features. I'm guessing at the time this table was created, the intention would've been to continually update this table as a "source of truth" for new features added to Worker Tier environments. However it seems we just use the regular release notes page to discuss updates to our platforms, so this table has not been updated in quite some time (years). 

Users may see this table and assume that no updates have been performed to Worker Tier environments since 2015, which is not the case. It looks misleading for this table to indicate that no updates have been performed in years. If we have a centralized release notes page already for EB, we don't need this additional table.

My recommendation would be to remove it. If you approve of this change, I'll be happy to submit a Pull Request to remove the table.

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html

**Comment by dankhen** [comment]
Thanks @Kausheel. I tend to agree. I'll discuss with the relevant SDE team and we'll decide how to proceed. (No need for a pull request - thanks!)
