### ISSUE TITLE
COMPOSER_AUTH environment variable is malformed, should be a valid JSON object

### ISSUE THREAD

**Issue by mozgbrasil** [awsdocs/aws-elastic-beanstalk-developer-guide#63]
https://github.com/magento/magento2/issues/22460

**Comment by mcdwil** [comment]
Hi @mozgbrasil ,

I'm sorry you were having trouble using Elastic Beanstalk. 

This repo is for discussing issues with, or suggesting edits of, the documentation, and not meant as a service support forum. If you need expert help, I can suggest the following:
- Our forum: https://forums.aws.amazon.com/forum.jspa?forumID=86
- AWS Support: https://aws.amazon.com/premiumsupport/

Thanks!
