### ISSUE TITLE
Needs to be updated from Python 2.7 to 3.x

### ISSUE THREAD

**Issue by beebus** [awsdocs/aws-elastic-beanstalk-developer-guide#79]
![image](https://user-images.githubusercontent.com/3438663/80897030-448b3180-8cba-11ea-8c20-4ce70348c755.png)

The above command gives the following error message:

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
 
If I setup the virtual environment with Python 3.8, then I don't receive any error messages.
Another correction is that the activate script is not in a Bin folder but rather the Scripts folder.

**Comment by dankhen** [comment]
@beebus Thanks. I'll check with the Elastic Beanstalk team and fix. I want to try and make this content version agnostic.
