### ISSUE TITLE
Example Flask app refers to the application variable incorrectly

### ISSUE THREAD

**Issue by greendinosaur** [awsdocs/aws-elastic-beanstalk-developer-guide#84]
I've been using the example Flask app to get an application up and running on elastic beanstalk.
I kept on getting a 502 nginx error and tracked it down to an error in the example.

The example refers to naming the app "application" as in
```
# EB looks for an 'application' callable by default.
application = Flask(__name__)
```
However, it needs to be named `app` and not `application`. This is what the default elastic beanstalk configuration calls when running the code hosted on the environment. When I changed the references inside application.py to app, the example app worked fine and no 502 errors.

**Comment by dankhen** [comment]
@greendinosaur Thanks. I'm finding out with the Beanstalk team. Mainly I'd like to know if this is a recent change or has always been the case (i.e. just a documentation bug).

**Comment by garrettjaeger** [comment]
@greendinosaur After doing some digging I’ve found out that this is indeed a discrepancy between the older Python platforms and the current Amazon Linux 2 (AL2) based Python platforms. 

In older Python platform versions, the default behavior is to serve the application instance named ‘application’ (the name of the flask variable in your case) within the Python module named ‘application’. However, in the AL2 Python platform the default behavior is to serve the application instance named ‘app’ inside of the Python module named ‘application’. 

We have found this to be an unnecessary difference in behavior between the older and newer Python platforms, so we will be updating our AL2 based Python platform to match the behavior of older platform versions by having the default application instance name to serve be ‘application’. We are planning on this fix being included in a coming AL2 Python platform release.

Until that update is out, here are a few workarounds for getting applications like this working:

1. Supply a Procfile which defines the Python module and application instance names that you are using. For example: 
`web: gunicorn --bind 127.0.0.1:8000 --workers=1 --threads=15 module_name:app_name`
Where module_name is the name of the Python module that your application resides in, and app_name is the name of the application instance within the module. Documentation for using a Procfile in Beanstalk Python platforms: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/python-configuration-procfile.html

2. If you want your application to work with the current default Beanstalk settings, change the name of the application instance within your application to be ‘app’, just like you did in this case.

3. Set the WSGIPath option setting to be ‘module_name:app_name’. This functions similarly to the Procfile workaround where you are setting the module name and application instance name you want to serve. Documentation for the WSGI Path option setting: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-container.html#python-namespaces

**Comment by dankhen** [comment]
Thanks for the update @garrettjaeger . I'm closing the issue.
