### ISSUE TITLE
Is there a way to deploy asp.net core web app using Github Action on AWS BeanStalk instance?

### ISSUE THREAD

**Issue by anomepani** [awsdocs/aws-elastic-beanstalk-developer-guide#92]
Is there a way to deploy asp.net core web app using Github Action on AWS BeanStalk instance?

I am looking for way to deploy my asp.net core web API  using Github Action on AWS Bean Stalk Instance and not able to find any docs and guidelines.

**Comment by dankhen** [comment]
I don't know of a direct integration (an AWS-developed GitHub Action for Elastic Beanstalk). From a cursory read of GitHub Actions documentation, it looks like it's very open ended - you could create a workflow that does whatever you need.

Related info:
- Elastic Beanstalk is integrated with git repositories through the EB CLI. See [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-cli-git.html).
- AWS has its own CICD service, [CodePipeline](https://docs.aws.amazon.com/codepipeline/latest/userguide/welcome.html). Elastic Beanstalk is integrated with CodePipeline in a specific way too - see [here](https://docs.aws.amazon.com/codepipeline/latest/userguide/integrations-action-type.html#integrations-deploy).
