### ISSUE TITLE
Custom libraries links

### ISSUE THREAD

**Issue by rennokki** [awsdocs/aws-elastic-beanstalk-developer-guide#95]
I have seen on https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-laravel-tutorial.html that there is a Laravel tutorial.

Any possibility of adding a link to my own custom library that guides users into building Laravel apps on top of Elastic Beanstalk? https://github.com/rennokki/laravel-aws-eb

**Comment by mrenneke-amazon** [comment]
Hi @rennokki -

Thank you for offering these instructions.  You did a great job describing the configuration and deployment.  

Unfortunately, we cannot link our service documentation to customer's private web sites.  But we would value your input through [pull requests](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/pulls) if you would ever like to add more helpful information, clarify or correct any content.

Sorry about how long it took us to get back to you.  Thanks again!
